### ISSUE TITLE
Package Bayes3D

### ISSUE THREAD

**Issue by srounce** [numtide/OpenGen.nix#2]
Package [probcomp/bayes3d](https://github.com/probcomp/bayes3d) as a Nix derivation.

### Dependencies
* [ ] numtide/OpenGen.nix#3
* [ ] numtide/OpenGen.nix#4
* [ ] numtide/OpenGen.nix#5
* [ ] numtide/OpenGen.nix#6
* [ ] numtide/OpenGen.nix#7
* [ ] numtide/OpenGen.nix#10
